root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "static", "node_modules", "docs", ".git"]
  exclude_regex = ["_test\\.go"]
  include_ext = ["go", "html"]
  include_dir = ["cmd", "internal", "templates"]
  kill_delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
